[package]
name = "overlay-ipc"
version = "0.1.0"
authors = ["Alex S"]
edition = "2021"

[dependencies]
futures     = "0.3.30"
ipc-channel = "=0.15.0" # 0.16 requires POLLRDHUP
lazy_static = "1.4.0"
serde       = "1.0.203"
zbus        = "4.2.2"
